cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:8181
file:
  upload-dir: /dev/UploadDir
spring:
  application:
    name: api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database_api?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false

    open-in-view: false

  servlet:
    multpart:
      enable: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  level:
    # root: WARN
    "[com.ssilvadev.api]": DEBUG
springdoc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
